AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Nearspark

Metadata:
  AWS::ServerlessRepo::Application:
    Name: nearspark
    Description: Image resizing services for Hubs Cloud
    Author: Mozilla
    SpdxLicenseId: MPL-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    SemanticVersion: 0.1.0

Parameters:
  NearsparkRoleArn:
    Type: String

Resources:
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Role:
      Ref: NearsparkRoleArn
    Properties:
      CodeUri: nearspark.zip
      Handler: index.thumbnail
      Runtime: nodejs10.x
      Timeout: 30
      MemorySize: 512

Outputs:
  NearsparkThumbnailFunctionArn:
    Description: "Thumbnail Lambda Function ARN"
    Value: !GetAtt ThumbnailFunction.Arn
